### ISSUE TITLE
求能直接跳转到交易所相关币种交易页面

### ISSUE THREAD

**Issue by L-JH** [elegantYU/xiaobi#11]
如币安火币等交易所：
ETH的现货：https://www.binance.com/zh-CN/trade/ETH_USDT?type=spot
LTC的逐仓10X：https://www.binance.com/zh-CN/trade/LTC_USDT?type=isolated
BTC的永续：https://www.binance.com/zh-CN/futures/BTCUSDT_perpetual
等等等，看好你哦~

**Comment by elegantYU** [comment]
好提议👍，已加入后续计划中

**Comment by justwink** [comment]
👍
