### ISSUE TITLE
每次更新一次就把自选清空了？

### ISSUE THREAD

**Issue by zhaoPengInGithub** [elegantYU/xiaobi#15]
- RT, 选了半天加了一大堆放自选里面，结果一会打开，崩个更新说明，自选列表就清空了？这样好像不太合理

**Comment by elegantYU** [comment]
是chrome还是火狐浏览器的插件呢，更新前是什么版本的

**Comment by zhaoPengInGithub** [comment]
chrome 最新版，现在版本是1.1.2，最近连着更新了两次了，应该不是太旧的版本

**Comment by elegantYU** [comment]
添加自选时的版本是1.1.1吗，自选之外的其他设置是否也被重置了

**Comment by elegantYU** [comment]
#9 

1.0.2版本之后的数据存储，由插件内存改为使用 chrome.storage.sync api存储数据，这个api存的数据除非手动删除，一般更新插件和开关插件都不会使数据丢失的。

可能是版本升级后清空了1.0.2版本的内部缓存，导致自选等数据被清了。

刚刚我本地1.1.1版本添加自选等数据后，更新插件没有发现自选等数据清空的现象...

**Comment by elegantYU** [comment]
下版本会加上数据备份的功能，可以进行数据同步和数据迁移

**Comment by zhaoPengInGithub** [comment]
那我再选一次试试看

**Comment by elegantYU** [comment]
可以试试在插件管理页面开关插件、退出浏览器清空缓存等操作，若还是有数据清空的问题我远程帮你看下
