### ISSUE TITLE
DASH/USDT 的价格显示不对

### ISSUE THREAD

**Issue by puteulanus** [elegantYU/xiaobi#16]
折线图和交易所那边的基本上是一致的，现在在 170 左右，但是 现价 和 高/低价 貌似有问题

涨跌幅好像也不对，火币那边今天 DASH 跌了 10%+ 了

![image](https://user-images.githubusercontent.com/4849177/121114327-17f30300-c846-11eb-8e76-70be2c8fd73c.png)

![image](https://user-images.githubusercontent.com/4849177/121114289-0873ba00-c846-11eb-8dee-69cf2a6c27ae.png)

**Comment by elegantYU** [comment]
可能是添加了其他平台的 DASH 币，在搜索的时候可以看到对应平台。

搜索是使用mytoken的接口，会随机返回其汇总的各个平台币种。

**Comment by L-JH** [comment]
每个币种的现价都不对，并且更新不及时，看了下，只有自带置顶的四个是对的

**Comment by elegantYU** [comment]
是这样的，榜单和搜索都是使用mytoken的接口获取数据，榜单内的币种价格不一定是自己所需对应平台的币种价格，搜索币的时候，在结果右侧有对应平台名称。置顶的四个也是我手动查找到的币种，附上的id
![image](https://user-images.githubusercontent.com/23764603/122725333-74730b00-d2a7-11eb-893c-d7e1bd3cf29a.png)

**Comment by elegantYU** [comment]
下版本会整合所有热门平台的币种搜索结果，重构下现有的搜索模块
