### ISSUE TITLE
添加记账系统

### ISSUE THREAD

**Issue by L-JH** [elegantYU/xiaobi#17]
期望添加记账系统，这可是个大工程哦

**Comment by elegantYU** [comment]
这个之前考虑过，但是不做的原因有二

- 虚拟币是短线操作，交易频繁，币种多的用户需要不断修正份额。这种操作量对插件来说不太合适
- ”小币“主要做的是币圈行情和资讯集合的，若加入货币份额操作，个人觉得还不如看手机更靠谱

>  插件目前还是以优化已有功能为主
