### ISSUE TITLE
上传配置无效

### ISSUE THREAD

**Issue by zhaoPengInGithub** [elegantYU/xiaobi#19]
最新版本1.2.0；macOS
从chrome导出的配置文件，再到firefox上进行导入，点完上传按钮，出现选文件的弹窗，但是此时插件界面收起来隐藏了，选完文件也什么都没有发生

**Comment by elegantYU** [comment]
刚刚注意到 firefox 这个问题，“input[type='file']打开本地文件夹时，firefox 插件的 popup会自动关闭”。

下个版本会增加一个用于上传配置的插件页面用来解决这个兼容性问题。😢
