### ISSUE TITLE
新版本的浏览器通知太频繁了。。。

### ISSUE THREAD

**Issue by RainshawGao** [elegantYU/xiaobi#22]
希望加个设置，可以关掉这个浏览器通知。。。。

**Comment by elegantYU** [comment]
好的🆗，会加上一个关闭通知的按钮

**Comment by elegantYU** [comment]
后面会考虑加一个关闭所有通知的开关

**Comment by RainshawGao** [comment]
我指的是那个平台数据的通知，mac上还好，关闭浏览器页面不会退出应用，但在win上，关了浏览器页面就退出了，再打开就会触发这个通知。

**Comment by elegantYU** [comment]
抱歉，最近一直没时间更新插件，稍等今晚就发版

**Comment by elegantYU** [comment]
1.3.1 版本已发布
