### ISSUE TITLE
涨跌幅颜色有问题

### ISSUE THREAD

**Issue by cute-angelia** [elegantYU/xiaobi#3]
<img width="514" alt="企业微信20210527-094711@2x" src="https://user-images.githubusercontent.com/26561606/119752968-8a6ff480-bed0-11eb-883d-27cf97e45f98.png">

涨跌幅颜色应该是绿色

**Comment by elegantYU** [comment]
涨跌颜色可以在设置里调整哦，绿涨红跌或绿跌红涨

**Comment by cute-angelia** [comment]
> 涨跌颜色可以在设置里调整哦，绿涨红跌或绿跌红涨

你仔细看看！

**Comment by cute-angelia** [comment]
我看错了。。
