### ISSUE TITLE
谷歌浏览器退出后会重置以往的设置

### ISSUE THREAD

**Issue by komorebi10086** [elegantYU/xiaobi#7]
1、在谷歌浏览器的应用中设置了小币中的自选以及颜色的区分，但在关闭浏览器之后再重新打开浏览器设置都会恢复为默认值。
2、来回切换自选以及涨幅榜的时候有事自选显示的页面会是涨幅榜的页面

**Comment by elegantYU** [comment]
## 退出浏览器清空数据
请问是否设置有退出浏览器清除cookie及网站数据的行为，因为自选数据和设置数据都是存放在插件内部的，所以如果有类似操作的话，数据是会被清空的

## 榜单切换数据未变化

这块是每个tab点击时都会请求不同的数据接口，可能是接口数据返回较慢，后面我会加上数据加载的loading，以免引起误会

**Comment by zhcode-fun** [comment]
看代码，是存在插件的localStorage里面，但是除了自定tab，其他设置都不保存，可看下面的录屏

https://user-images.githubusercontent.com/31911177/119851543-10c41f00-bf41-11eb-836d-6cf81582a847.mp4

**Comment by elegantYU** [comment]
> 看代码，是存在插件的localStorage里面，但是除了自定tab，其他设置都不保存，可看下面的录屏
> 
> ![QQ录屏](https://user-images.githubusercontent.com/31911177/119851854-5b459b80-bf41-11eb-80bc-066b9358faae.gif)

是的，设置内容现在是分为 localStorage 和 内存中的 `src/services/Store`，由于localStorage大小限制，开始时就把用户自设的相关数据存入Store中，设置的改变会通过插件的eventbus传递。

**Comment by elegantYU** [comment]
下版本将使用插件 storage 权限去写入数据
