### ISSUE TITLE
建议把特殊关注的数值改为精确或者可配置，因为四舍五入误差就比较大🤪

### ISSUE THREAD

**Issue by hejunping** [elegantYU/xiaobi#8]

**Comment by elegantYU** [comment]
嗯嗯，1.0.2版本对于这块做了点处理，特殊关注的功能后面还会做更多可操作性的开发的🤓

**Comment by anhenghuang** [comment]
+1
比如ETH/USDT现在=2789，缩略图里是 2.8K。像SHIB/USDT，缩略图里会是0.000。希望能有进一步的优化，谢谢大佬提供的工具 👍
