### ISSUE TITLE
1.1.1版本更新详情

### ISSUE THREAD

**Issue by elegantYU** [elegantYU/xiaobi#9]
## 浏览器退出后(可能包含清除缓存记录操作)，导致数据和设置都丢失

这个是因为之前的插件数据存储是在 `background` 一个数据管理的Store文件内，是记录在内存中的(避免了存储上限的问题)。

但是，却忽略了有退出清除缓存记录的操作(推眼镜)，导致插件内的数据信息每次打开浏览器都是空白的。

现在使用了 [chrome.storage.sync](https://developer.chrome.com/docs/extensions/reference/storage/#property-sync) api做数据存储，同时优化了存储的数据结构，不会再出现清空缓存数据丢失的问题。

## badge和其他数据精度问题

之前直接使用 `toFixed` 暴力的处理数据，导致很多数据会四舍五入进位。

现在优化了数据保留小数点位数的方法，保证了精度。

eg:
```
1.56 => '1.5'
9999 => '9.9K'
0.00088 => '0.0008'
```

## badge数据显示问题
chrome的badge文本长度是 `4.5` 字符，是4个数字/字母 + 小数点，这样挤一点但还是能显示完整的。

周末适配火狐的时候，发现火狐是只能4个字符(包括小数点)，没办法，只能忍痛再砍一刀
![image](https://user-images.githubusercontent.com/23764603/120127646-84d91e00-c1f2-11eb-83c4-98c8ff142ef9.png)
火狐内显示

#5 查看详细数据信息

特殊关注这块数据的操作，目前还在设计中，会包括显示数据类型切换，实时通知等功能。

## 小窗模式

可以右键打开独立窗口，摸鱼更隐蔽，切换更快捷

**Comment by L-JH** [comment]
火狐调整窗口大小失败...

**Comment by L-JH** [comment]
火狐不能保存自选，不知为啥，过一会自选就不在了;
火狐不能创建提醒
火狐版本是ESR78

**Comment by elegantYU** [comment]
@L-JH 火狐市场中小币最新版本是1.1.1，78ESR版本我刚测试过，自选和通知是可以保存数据的
